const COMPLETED_LOGIN_SUCCESS = 'COMPLETED_LOGIN_SUCCESS';
const COMPLETED_LOGIN_FAIL = 'COMPLETED_LOGIN_FAIL';
const RESET_REQUEST = 'RESET_REQUEST';

export default {
  COMPLETED_LOGIN_SUCCESS,
  COMPLETED_LOGIN_FAIL,
  RESET_REQUEST
};