const SET_USERNAME='SET_USERNAME';
const SET_LOGGEDIN='SET_LOGGEDIN';
const SET_LOGGEDOUT='SET_LOGGEDOUT'
const SET_MONEY='SET_MONEY';

export default {
    SET_USERNAME,
    SET_LOGGEDIN,
    SET_LOGGEDOUT,
    SET_MONEY
}