const COMPLETED_CREATE_ACCOUNT_SUCCESS = 'COMPLETED_CREATE_ACCOUNT_SUCCESS';
const COMPLETED_CREATE_ACCOUNT_FAIL = 'COMPLETED_CREATE_ACCOUNT_FAIL';
const RESET_CREATE_ACCOUNT_STATE = 'RESET_CREATE_ACCOUNT_STATE';

export default {
  COMPLETED_CREATE_ACCOUNT_SUCCESS,
  COMPLETED_CREATE_ACCOUNT_FAIL,
  RESET_CREATE_ACCOUNT_STATE
};
